version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-catalog-app
    ports:
      - 3001:3000
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/home/node/app
    networks:
      - app-network
      - codeflix_rabbitmq_micro-catalog

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - 'discovery.type=single-node'
    networks:
      - app-network
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - app-network
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  app-network:
    driver: bridge
  codeflix_rabbitmq_micro-catalog:
    external: true
