version: "3"

services:
  app:
    build:
      context: node_app
    tty: true
    container_name: node_app
    entrypoint: dockerize -wait tcp://banco:3306 -timeout 20s node index.js
    volumes:
      - ./node_app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - appnet
    ports:
      - "3000:3000"
    depends_on:
      - banco

  banco:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=desafio2
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - appnet
    volumes:
      - ./mysql:/var/lib/mysql
    command: --innodb-use-native-aio=0
    container_name: banco_dados_mysql
    restart: always
    ports:
      - "3306:3306"
    tty: true

  proxy:
    build:
      context: nginx
    container_name: nginx_proxy
    networks:
      - appnet
    ports:
      - "8080:80"

networks:
  appnet:
    driver: bridge
